#!/usr/bin/env python3
"""Generate the Unicode-9 assigned-range table used by Task 2.3 NFC."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


EXPECTED_SHA256 = "5cb15b04693c43df16e0d304deca049e93b001445d163184e0ff1b7c8c852146"
LINE = re.compile(r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*([0-9]+\.[0-9]+)\s*(?:#.*)?$")


def generate(source: Path) -> bytes:
    data = source.read_bytes()
    if hashlib.sha256(data).hexdigest() != EXPECTED_SHA256:
        raise ValueError("Unicode 9 DerivedAge.txt SHA-256 mismatch")
    raw_ranges: list[tuple[int, int]] = []
    for raw in data.decode("utf-8-sig").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = LINE.match(line)
        if match is None:
            raise ValueError(f"malformed DerivedAge row: {line}")
        start = int(match.group(1), 16)
        end = int(match.group(2) or match.group(1), 16)
        age = tuple(int(part) for part in match.group(3).split("."))
        if age > (9, 0):
            raise ValueError("pinned Unicode 9 file contains a future age")
        raw_ranges.append((start, end))
    ranges: list[tuple[int, int]] = []
    for start, end in sorted(raw_ranges):
        if ranges and start <= ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], max(ranges[-1][1], end))
        else:
            ranges.append((start, end))
    if not ranges or ranges[0][0] != 0 or ranges[-1][1] > 0x10FFFF:
        raise ValueError("Unicode 9 assigned ranges failed structural checks")
    lines = [
        "/* Generated by tools/generate-unicode9-assigned.py.",
        " * Source: Unicode 9.0.0 UCD DerivedAge.txt",
        f" * Source SHA-256: {EXPECTED_SHA256}",
        " * Unicode data license: third_party/utf8proc/LICENSE.md",
        " */",
        f"#define KQ_UNICODE9_ASSIGNED_RANGE_COUNT {len(ranges)}U",
        "static const uint32_t kq_unicode9_assigned_ranges[][2] = {",
    ]
    lines.extend(f"    {{0x{start:06x}U, 0x{end:06x}U}}," for start, end in ranges)
    lines.extend(["};", ""])
    return "\n".join(lines).encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--derived-age", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    output = generate(args.derived_age)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(output)
    print(
        f"output={args.output} sha256={hashlib.sha256(output).hexdigest()} "
        f"bytes={len(output)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
